name: Build the file

on:
  push:
    branches: [ build-the** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: See the content
        run: |
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install doxygen
          doxygen --version
