name: Build the file

on:
  push:
    branches: [ build-the** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache doxygen
        uses: actions/cache@v2
        with:
          path: doxygen-1.9.2.linux.bin.tar.*
          key: doxygen-1.9.2.linux.bin.tar.

      - name: See the content
        run: |
          sudo apt-get install libclang-9-dev
          sudo apt-get install libclang-cpp9
          if [ ! -f doxygen-1.9.2.linux.bin.tar.* ]; then wget https://github.com/doki-nordic/test-actions-playground/raw/doxygen-ubuntu-bins/doxygen-1.9.2.linux.bin.tar.xz || true; fi
          if [ ! -f doxygen-1.9.2.linux.bin.tar.* ]; then wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz || true; fi
          tar -xf doxygen-1.9.2.linux.bin.tar.*
          echo `pwd`/doxygen-1.9.2/bin >> $GITHUB_PATH
          export PATH=$PATH:`pwd`/doxygen-1.9.2/bin
          which doxygen
          doxygen --version
